// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_OVERLAY_H
#define UI_OVERLAY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Overlay
extern void ui_Overlay_screen_init(void);
extern void ui_Overlay_screen_destroy(void);
extern lv_obj_t * ui_Overlay;
extern lv_obj_t * ui_containerOverlay;
extern lv_obj_t * ui_btnAudio;
extern lv_obj_t * ui_btnBLE;
extern lv_obj_t * ui_btnWiFi;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

