// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_WIFI_SETTINGS_H
#define UI_WIFI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WIFI_Settings
extern void ui_WIFI_Settings_screen_init(void);
extern void ui_WIFI_Settings_screen_destroy(void);
extern lv_obj_t * ui_WIFI_Settings;
extern lv_obj_t * ui_Panel;
extern lv_obj_t * ui_BtnConnect;
extern lv_obj_t * ui_TxtConnect;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_TxtWIFI;
extern lv_obj_t * ui_InputSSIDs;
extern lv_obj_t * ui_TxtPassword;
extern lv_obj_t * ui_InputPassword;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

