// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_KEYBOARD_SETTINGS_H
#define UI_KEYBOARD_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Keyboard_Settings
extern void ui_Keyboard_Settings_screen_init(void);
extern void ui_Keyboard_Settings_screen_destroy(void);
extern lv_obj_t * ui_Keyboard_Settings;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_TxtKeyboard;
extern lv_obj_t * ui_InputBLEs;
extern lv_obj_t * ui_BtnConnectBLE;
extern lv_obj_t * ui_TxtConnectBLE;
extern lv_obj_t * ui_BtnScan;
extern lv_obj_t * ui_TxtScanBLE;
extern lv_obj_t * ui_InputTest;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

