// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_TxtWord = NULL;
lv_obj_t * ui_InputWord = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_TxtExplanation = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_TxtSampleSentence = NULL;
lv_obj_t * ui_LookingUpBar = NULL;
// event funtions

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtWord = lv_label_create(ui_Main);
    lv_obj_set_height(ui_TxtWord, 17);
    lv_obj_set_width(ui_TxtWord, lv_pct(100));
    lv_obj_set_x(ui_TxtWord, 10);
    lv_obj_set_y(ui_TxtWord, 10);
    lv_label_set_text(ui_TxtWord, "TxtWord");
    lv_obj_set_style_text_color(ui_TxtWord, lv_color_hex(0x000A93), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtWord, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TxtWord, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputWord = lv_textarea_create(ui_Main);
    lv_obj_set_width(ui_InputWord, lv_pct(100));
    lv_obj_set_height(ui_InputWord, LV_SIZE_CONTENT);    /// 70
    lv_textarea_set_text(ui_InputWord, "InputWord");
    lv_textarea_set_placeholder_text(ui_InputWord, "Enter a word...");
    lv_textarea_set_one_line(ui_InputWord, true);
    lv_obj_add_flag(ui_InputWord, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_InputWord, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_InputWord, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_InputWord, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_InputWord, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InputWord, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InputWord, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_InputWord, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_InputWord, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Panel1, 315);
    lv_obj_set_height(ui_Panel1, 205);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 33);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_TxtExplanation = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_TxtExplanation, lv_pct(100));
    lv_obj_set_height(ui_TxtExplanation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TxtExplanation, 65);
    lv_obj_set_y(ui_TxtExplanation, 46);
    lv_label_set_text(ui_TxtExplanation,
                      "Hallelujah is an expression of rejoicing and praise, often used to express gratitude or joy, especially in a religious context.");
    lv_obj_set_style_text_letter_space(ui_TxtExplanation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TxtExplanation, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TxtExplanation, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel1);
    lv_obj_set_height(ui_Panel2, 1);
    lv_obj_set_width(ui_Panel2, lv_pct(100));
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TxtSampleSentence = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_TxtSampleSentence, lv_pct(100));
    lv_obj_set_height(ui_TxtSampleSentence, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TxtSampleSentence, 5);
    lv_obj_set_y(ui_TxtSampleSentence, 150);
    lv_label_set_text(ui_TxtSampleSentence,
                      "When the storm cleared and the sun shone brightly, the villagers shouted 'hallelujah' in relief and thanks.");
    lv_obj_set_style_text_color(ui_TxtSampleSentence, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtSampleSentence, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TxtSampleSentence, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TxtSampleSentence, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TxtSampleSentence, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LookingUpBar = lv_bar_create(ui_Main);
    lv_obj_set_height(ui_LookingUpBar, 10);
    lv_obj_set_width(ui_LookingUpBar, lv_pct(100));
    lv_obj_set_align(ui_LookingUpBar, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_LookingUpBar, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_LookingUpBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LookingUpBar, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LookingUpBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_LookingUpBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LookingUpBar, lv_color_hex(0xAAAAAA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LookingUpBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_LookingUpBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_LookingUpBar,
                                                                                                   lv_obj_get_style_pad_right(ui_LookingUpBar, LV_PART_MAIN) + 1, LV_PART_MAIN);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_TxtWord = NULL;
    ui_InputWord = NULL;
    ui_Panel1 = NULL;
    ui_TxtExplanation = NULL;
    ui_Panel2 = NULL;
    ui_TxtSampleSentence = NULL;
    ui_LookingUpBar = NULL;

}
