// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_TxtWord;
extern lv_obj_t * ui_InputWord;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_TxtExplanation;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_TxtSampleSentence;
extern lv_obj_t * ui_LookingUpBar;
extern lv_obj_t * ui_IcoStatus;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

