// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Overlay = NULL;
lv_obj_t * ui_containerOverlay = NULL;
lv_obj_t * ui_btnAudio = NULL;
lv_obj_t * ui_btnBLE = NULL;
lv_obj_t * ui_btnWiFi = NULL;
// event funtions

// build funtions

void ui_Overlay_screen_init(void)
{
    ui_Overlay = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Overlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_containerOverlay = lv_obj_create(ui_Overlay);
    lv_obj_remove_style_all(ui_containerOverlay);
    lv_obj_set_width(ui_containerOverlay, 66);
    lv_obj_set_height(ui_containerOverlay, 24);
    lv_obj_set_align(ui_containerOverlay, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_containerOverlay, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_containerOverlay, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_containerOverlay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_containerOverlay, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_containerOverlay, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_containerOverlay, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_containerOverlay, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnAudio = lv_button_create(ui_containerOverlay);
    lv_obj_set_width(ui_btnAudio, 10);
    lv_obj_set_height(ui_btnAudio, 10);
    lv_obj_set_align(ui_btnAudio, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnAudio, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnAudio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnAudio, lv_color_hex(0xCE45DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnAudio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBLE = lv_button_create(ui_containerOverlay);
    lv_obj_set_width(ui_btnBLE, 10);
    lv_obj_set_height(ui_btnBLE, 10);
    lv_obj_set_align(ui_btnBLE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBLE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnBLE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnWiFi = lv_button_create(ui_containerOverlay);
    lv_obj_set_width(ui_btnWiFi, 10);
    lv_obj_set_height(ui_btnWiFi, 10);
    lv_obj_set_align(ui_btnWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnWiFi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnWiFi, lv_color_hex(0x0ABF0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Overlay_screen_destroy(void)
{
    if(ui_Overlay) lv_obj_del(ui_Overlay);

    // NULL screen variables
    ui_Overlay = NULL;
    ui_containerOverlay = NULL;
    ui_btnAudio = NULL;
    ui_btnBLE = NULL;
    ui_btnWiFi = NULL;

}
