// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_WIFI_Settings = NULL;
lv_obj_t * ui_Panel = NULL;
lv_obj_t * ui_BtnConnect = NULL;
lv_obj_t * ui_TxtConnect = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_TxtWIFI = NULL;
lv_obj_t * ui_InputSSIDs = NULL;
lv_obj_t * ui_TxtPassword = NULL;
lv_obj_t * ui_InputPassword = NULL;
// event funtions

// build funtions

void ui_WIFI_Settings_screen_init(void)
{
    ui_WIFI_Settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WIFI_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel = lv_obj_create(ui_WIFI_Settings);
    lv_obj_set_width(ui_Panel, lv_pct(100));
    lv_obj_set_height(ui_Panel, lv_pct(100));
    lv_obj_set_align(ui_Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnConnect = lv_button_create(ui_Panel);
    lv_obj_set_width(ui_BtnConnect, 100);
    lv_obj_set_height(ui_BtnConnect, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_BtnConnect, -3);
    lv_obj_set_y(ui_BtnConnect, 81);
    lv_obj_set_align(ui_BtnConnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TxtConnect = lv_label_create(ui_BtnConnect);
    lv_obj_set_width(ui_TxtConnect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TxtConnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TxtConnect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TxtConnect, "Connect");
    lv_obj_set_style_text_font(ui_TxtConnect, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Panel);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 10);
    lv_obj_set_align(ui_Container1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TxtWIFI = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_TxtWIFI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TxtWIFI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TxtWIFI, 30);
    lv_obj_set_y(ui_TxtWIFI, 26);
    lv_label_set_text(ui_TxtWIFI, "WIFI:");
    lv_obj_set_style_text_font(ui_TxtWIFI, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputSSIDs = lv_dropdown_create(ui_Container1);
    lv_dropdown_set_options(ui_InputSSIDs, "Option 1\nOption 2\nOption 3");
    lv_obj_set_width(ui_InputSSIDs, 204);
    lv_obj_set_height(ui_InputSSIDs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InputSSIDs, 97);
    lv_obj_set_y(ui_InputSSIDs, 15);
    lv_obj_add_flag(ui_InputSSIDs, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_InputSSIDs, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_InputSSIDs), &lv_font_montserrat_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtPassword = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_TxtPassword, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TxtPassword, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TxtPassword, 15);
    lv_obj_set_y(ui_TxtPassword, 94);
    lv_label_set_text(ui_TxtPassword, "Password:");
    lv_obj_set_style_text_font(ui_TxtPassword, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputPassword = lv_textarea_create(ui_Container1);
    lv_obj_set_width(ui_InputPassword, 198);
    lv_obj_set_height(ui_InputPassword, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_InputPassword, 100);
    lv_obj_set_y(ui_InputPassword, 82);
    lv_textarea_set_placeholder_text(ui_InputPassword, "Placeholder...");
    lv_textarea_set_one_line(ui_InputPassword, true);
    lv_obj_set_style_text_font(ui_InputPassword, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_WIFI_Settings_screen_destroy(void)
{
    if(ui_WIFI_Settings) lv_obj_del(ui_WIFI_Settings);

    // NULL screen variables
    ui_WIFI_Settings = NULL;
    ui_Panel = NULL;
    ui_BtnConnect = NULL;
    ui_TxtConnect = NULL;
    ui_Container1 = NULL;
    ui_TxtWIFI = NULL;
    ui_InputSSIDs = NULL;
    ui_TxtPassword = NULL;
    ui_InputPassword = NULL;

}
